index:
  path: /
  controller: App\Controller\NotesController::index

get:
  path: /display
  controller: App\Controller\NotesController::display

post:
  path: /create
  controller: App\Controller\NotesController::create

save:
  path: /save
  controller: App\Controller\NotesController::saveNote
