index:
  path: /
  controller: App\Controller\NotesController::index

display:
  path: /display
  controller: App\Controller\NotesController::display

create:
  path: /create
  controller: App\Controller\NotesController::create

save:
  path: /save
  controller: App\Controller\NotesController::saveNote

edit:
  path: /edit/{id}
  controller: App\Controller\NotesController::edit

update:
  path: /update
  controller: App\Controller\NotesController::update

delete:
  path: /delete
  controller: App\Controller\NotesController::delete
